"""Generate src/combocurve_api_helper/econ_models/_csv_generated.py.

Emits a `<method_base>_to_csv_rows` / `<method_base>_from_csv_rows` pair for every
econ-model type in econModels.json that has a registered mapper (i.e. `econModelType`
is a key of `econ_models.registry.MAPPERS`). The pair is thin sugar over
`get_mapper(econModelType)` -- it exists so each type has an explicit named function,
matching the per-type convention used elsewhere (e.g. `get_<method_base>_models`),
instead of forcing callers through the generic `get_mapper`.

Run: python scripts/generate_csv_functions.py          # writes the file
     python scripts/generate_csv_functions.py --stdout # prints (used by tests)
"""

from __future__ import annotations
import sys
import pathlib
from combocurve_api_helper import config
from combocurve_api_helper.econ_models.registry import MAPPERS

HEADER = '''\
# DO NOT EDIT -- generated by scripts/generate_csv_functions.py from econModels.json + the mapper registry.
# Re-run that script after adding/removing a mapper or changing econModels.json.
"""Per-type CSV convenience functions (generated).

Thin, explicit wrappers over `registry.get_mapper(...)` so each econ-model type has named
`<type>_to_csv_rows`/`<type>_from_csv_rows` (row level), `<type>_to_csv`/`<type>_from_csv`
(whole multi-model file, string in/out), and a `get_<type>_mapper()` accessor -- matching the
per-type function convention used elsewhere in the package rather than requiring callers to reach
for the generic `get_mapper`.
"""
from __future__ import annotations

from typing import Any, Dict, List, Optional, TextIO, Union

from .base import Context, EconModelMapper
from .registry import get_mapper
'''

FUNCS = '''

def {method_base}_to_csv_rows(model: Dict[str, Any], context: Optional[Context] = None) -> List[Dict[str, str]]:
    """Convert one `{econ_model_type}` econ-model API dict to CSV rows (model-level export shape)."""
    return get_mapper('{econ_model_type}').to_csv_rows(model, context)


def {method_base}_from_csv_rows(rows: List[Dict[str, str]]) -> Dict[str, Any]:
    """Reconstruct {article} `{econ_model_type}` econ-model API dict from its CSV rows."""
    return get_mapper('{econ_model_type}').from_csv_rows(rows)


def {method_base}_to_csv(models: List[Dict[str, Any]], context: Optional[Context] = None) -> str:
    """Serialize a list of `{econ_model_type}` econ-model API dicts to a multi-model CSV string."""
    return get_mapper('{econ_model_type}').to_csv(models, context)


def {method_base}_from_csv(source: Union[str, TextIO]) -> List[Dict[str, Any]]:
    """Parse {article} `{econ_model_type}` CSV (string or file-like) into a list of econ-model API dicts."""
    return get_mapper('{econ_model_type}').from_csv(source)


def get_{method_base}_mapper() -> EconModelMapper:
    """Return the singleton mapper for `{econ_model_type}`."""
    return get_mapper('{econ_model_type}')
'''


def render() -> str:
    """Render `_csv_generated.py`'s source: a to/from pair per mapper-backed econ-model type."""
    parts = [HEADER]
    names: list[str] = []
    for model_entry in config.ECON_MODELS:
        method_base, econ_model_type = model_entry['methodBase'], model_entry['econModelType']
        if econ_model_type not in MAPPERS:
            continue
        if not method_base:
            raise ValueError(f'econModelType {econ_model_type!r} has a mapper but no methodBase in econModels.json')
        article = 'an' if econ_model_type[:1].upper() in 'AEIOU' else 'a'
        parts.append(FUNCS.format(method_base=method_base, econ_model_type=econ_model_type, article=article))
        names.extend(
            (
                f'{method_base}_to_csv_rows',
                f'{method_base}_from_csv_rows',
                f'{method_base}_to_csv',
                f'{method_base}_from_csv',
                f'get_{method_base}_mapper',
            )
        )
    all_body = ''.join(f'    {name!r},\n' for name in names)
    parts.append(f'\n\n__all__ = [\n{all_body}]\n')
    return ''.join(parts)


def main() -> None:
    """Write the generated module to disk, or print it to stdout with `--stdout` (used by tests)."""
    text = render()
    if '--stdout' in sys.argv:
        sys.stdout.write(text)
        return
    out = (
        pathlib.Path(__file__).resolve().parents[1]
        / 'src'
        / 'combocurve_api_helper'
        / 'econ_models'
        / '_csv_generated.py'
    )
    out.write_text(text, encoding='utf-8')
    print(f'wrote {out}')


if __name__ == '__main__':
    main()
