"""Generate src/combocurve_api_helper/_models_generated.py from econModels.json.

Run: python scripts/generate_model_methods.py          # writes the file
     python scripts/generate_model_methods.py --stdout # prints (used by tests)
"""
from __future__ import annotations
import sys
import pathlib
from combocurve_api_helper import config

HEADER = '''\
# DO NOT EDIT -- generated by scripts/generate_model_methods.py from econModels.json.
# Re-run that script after changing econModels.json.
from __future__ import annotations

from typing import Dict, List, Optional, Union

from requests import Response

from .base import Item, ItemList
from ._econ_model_base import _EconModelMethodsBase


class _GeneratedModelMethods(_EconModelMethodsBase):
    """Per-type econ-model methods (generated). Mixed into Models."""
'''

CRUD = '''
    def get_{b}_models_url(self, project_id: str, filters: Optional[Dict[str, str]] = None) -> str:
        return self.get_econ_models_by_type_url(project_id, "{t}", filters)

    def get_{b}_models(self, project_id: str, filters: Optional[Dict[str, str]] = None) -> ItemList:
        return self.get_econ_models_by_type(project_id, "{t}", filters)

    def get_{b}_model_by_id_url(self, project_id: str, model_id: str,
                                filters: Optional[Dict[str, str]] = None) -> str:
        return self.get_econ_model_by_type_by_id_url(project_id, "{t}", model_id, filters)

    def get_{b}_model_by_id(self, project_id: str, model_id: str) -> Union[Item, None]:
        return self.get_econ_model_by_type_by_id(project_id, "{t}", model_id)
'''

ASSIGN = '''
    def get_{b}_assignments_by_id_url(self, project_id: str, model_id: str,
                                      filters: Optional[Dict[str, str]] = None) -> str:
        return self.get_econ_model_assignments_by_type_by_id_url(project_id, "{t}", model_id, filters)

    def get_{b}_assignments_by_id(self, project_id: str, model_id: str) -> Union[ItemList, None]:
        return self.get_econ_model_assignments_by_type_by_id(project_id, "{t}", model_id)

    def post_{b}_assignments_by_id(self, project_id: str, model_id: str, data: ItemList) -> ItemList:
        return self.post_econ_model_assignments_by_type_by_id(project_id, "{t}", model_id, data)

    def put_{b}_assignments_by_id(self, project_id: str, model_id: str, data: ItemList) -> ItemList:
        return self.put_econ_model_assignments_by_type_by_id(project_id, "{t}", model_id, data)

    def delete_{b}_assignments_by_id(self, project_id: str, model_id: str, scenario_id: str,
                                     qualifier_name: Optional[str] = None, wells: Optional[str] = None,
                                     all_wells: Optional[bool] = None) -> List[Response]:
        return self.delete_econ_model_assignments_by_type_by_id(
            project_id, "{t}", model_id, scenario_id, qualifier_name, wells, all_wells)
'''


def render() -> str:
    parts = [HEADER]
    for m in config.ECON_MODELS:
        b, t = m["methodBase"], m["econModelType"]
        if m["hasCrud"]:
            parts.append(CRUD.format(b=b, t=t))
        if m["assignable"]:
            parts.append(ASSIGN.format(b=b, t=t))
    return "".join(parts)


def main() -> None:
    text = render()
    if "--stdout" in sys.argv:
        sys.stdout.write(text)
        return
    out = pathlib.Path(__file__).resolve().parents[1] / "src" / "combocurve_api_helper" / "_models_generated.py"
    out.write_text(text, encoding="utf-8")
    print(f"wrote {out}")


if __name__ == "__main__":
    main()
