# DO NOT EDIT -- generated by scripts/generate_model_methods.py from econModels.json.
# Re-run that script after changing econModels.json.
from __future__ import annotations

from typing import Dict, Optional, Union

from .base import Item, ItemList
from ._econ_model_base import _EconModelMethodsBase


class _GeneratedModelMethods(_EconModelMethodsBase):
    """Per-type econ-model methods (generated). Mixed into Models."""

    def get_general_options_models_url(self, project_id: str, filters: Optional[Dict[str, str]] = None) -> str:
        return self.get_econ_models_by_type_url(project_id, "GeneralOptions", filters)

    def get_general_options_models(self, project_id: str, filters: Optional[Dict[str, str]] = None) -> ItemList:
        return self.get_econ_models_by_type(project_id, "GeneralOptions", filters)

    def get_general_options_model_by_id_url(self, project_id: str, model_id: str,
                                filters: Optional[Dict[str, str]] = None) -> str:
        return self.get_econ_model_by_type_by_id_url(project_id, "GeneralOptions", model_id, filters)

    def get_general_options_model_by_id(self, project_id: str, model_id: str) -> Union[Item, None]:
        return self.get_econ_model_by_type_by_id(project_id, "GeneralOptions", model_id)

    def get_actual_forecast_models_url(self, project_id: str, filters: Optional[Dict[str, str]] = None) -> str:
        return self.get_econ_models_by_type_url(project_id, "ActualOrForecast", filters)

    def get_actual_forecast_models(self, project_id: str, filters: Optional[Dict[str, str]] = None) -> ItemList:
        return self.get_econ_models_by_type(project_id, "ActualOrForecast", filters)

    def get_actual_forecast_model_by_id_url(self, project_id: str, model_id: str,
                                filters: Optional[Dict[str, str]] = None) -> str:
        return self.get_econ_model_by_type_by_id_url(project_id, "ActualOrForecast", model_id, filters)

    def get_actual_forecast_model_by_id(self, project_id: str, model_id: str) -> Union[Item, None]:
        return self.get_econ_model_by_type_by_id(project_id, "ActualOrForecast", model_id)

    def get_actual_forecast_assignments_by_id_url(self, project_id: str, model_id: str,
                                      filters: Optional[Dict[str, str]] = None) -> str:
        return self.get_econ_model_assignments_by_type_by_id_url(project_id, "ActualOrForecast", model_id, filters)

    def get_actual_forecast_assignments_by_id(self, project_id: str, model_id: str) -> Union[ItemList, None]:
        return self.get_econ_model_assignments_by_type_by_id(project_id, "ActualOrForecast", model_id)

    def post_actual_forecast_assignments_by_id(self, project_id: str, model_id: str, data: ItemList) -> ItemList:
        return self.post_econ_model_assignments_by_type_by_id(project_id, "ActualOrForecast", model_id, data)

    def put_actual_forecast_assignments_by_id(self, project_id: str, model_id: str, data: ItemList) -> ItemList:
        return self.put_econ_model_assignments_by_type_by_id(project_id, "ActualOrForecast", model_id, data)

    def delete_actual_forecast_assignments_by_id(self, project_id: str, model_id: str, data: ItemList) -> ItemList:
        return self.delete_econ_model_assignments_by_type_by_id(project_id, "ActualOrForecast", model_id, data)

    def get_capex_models_url(self, project_id: str, filters: Optional[Dict[str, str]] = None) -> str:
        return self.get_econ_models_by_type_url(project_id, "Capex", filters)

    def get_capex_models(self, project_id: str, filters: Optional[Dict[str, str]] = None) -> ItemList:
        return self.get_econ_models_by_type(project_id, "Capex", filters)

    def get_capex_model_by_id_url(self, project_id: str, model_id: str,
                                filters: Optional[Dict[str, str]] = None) -> str:
        return self.get_econ_model_by_type_by_id_url(project_id, "Capex", model_id, filters)

    def get_capex_model_by_id(self, project_id: str, model_id: str) -> Union[Item, None]:
        return self.get_econ_model_by_type_by_id(project_id, "Capex", model_id)

    def get_capex_assignments_by_id_url(self, project_id: str, model_id: str,
                                      filters: Optional[Dict[str, str]] = None) -> str:
        return self.get_econ_model_assignments_by_type_by_id_url(project_id, "Capex", model_id, filters)

    def get_capex_assignments_by_id(self, project_id: str, model_id: str) -> Union[ItemList, None]:
        return self.get_econ_model_assignments_by_type_by_id(project_id, "Capex", model_id)

    def post_capex_assignments_by_id(self, project_id: str, model_id: str, data: ItemList) -> ItemList:
        return self.post_econ_model_assignments_by_type_by_id(project_id, "Capex", model_id, data)

    def put_capex_assignments_by_id(self, project_id: str, model_id: str, data: ItemList) -> ItemList:
        return self.put_econ_model_assignments_by_type_by_id(project_id, "Capex", model_id, data)

    def delete_capex_assignments_by_id(self, project_id: str, model_id: str, data: ItemList) -> ItemList:
        return self.delete_econ_model_assignments_by_type_by_id(project_id, "Capex", model_id, data)

    def get_date_settings_models_url(self, project_id: str, filters: Optional[Dict[str, str]] = None) -> str:
        return self.get_econ_models_by_type_url(project_id, "Dates", filters)

    def get_date_settings_models(self, project_id: str, filters: Optional[Dict[str, str]] = None) -> ItemList:
        return self.get_econ_models_by_type(project_id, "Dates", filters)

    def get_date_settings_model_by_id_url(self, project_id: str, model_id: str,
                                filters: Optional[Dict[str, str]] = None) -> str:
        return self.get_econ_model_by_type_by_id_url(project_id, "Dates", model_id, filters)

    def get_date_settings_model_by_id(self, project_id: str, model_id: str) -> Union[Item, None]:
        return self.get_econ_model_by_type_by_id(project_id, "Dates", model_id)

    def get_date_settings_assignments_by_id_url(self, project_id: str, model_id: str,
                                      filters: Optional[Dict[str, str]] = None) -> str:
        return self.get_econ_model_assignments_by_type_by_id_url(project_id, "Dates", model_id, filters)

    def get_date_settings_assignments_by_id(self, project_id: str, model_id: str) -> Union[ItemList, None]:
        return self.get_econ_model_assignments_by_type_by_id(project_id, "Dates", model_id)

    def post_date_settings_assignments_by_id(self, project_id: str, model_id: str, data: ItemList) -> ItemList:
        return self.post_econ_model_assignments_by_type_by_id(project_id, "Dates", model_id, data)

    def put_date_settings_assignments_by_id(self, project_id: str, model_id: str, data: ItemList) -> ItemList:
        return self.put_econ_model_assignments_by_type_by_id(project_id, "Dates", model_id, data)

    def delete_date_settings_assignments_by_id(self, project_id: str, model_id: str, data: ItemList) -> ItemList:
        return self.delete_econ_model_assignments_by_type_by_id(project_id, "Dates", model_id, data)

    def get_depreciation_models_url(self, project_id: str, filters: Optional[Dict[str, str]] = None) -> str:
        return self.get_econ_models_by_type_url(project_id, "Depreciation", filters)

    def get_depreciation_models(self, project_id: str, filters: Optional[Dict[str, str]] = None) -> ItemList:
        return self.get_econ_models_by_type(project_id, "Depreciation", filters)

    def get_depreciation_model_by_id_url(self, project_id: str, model_id: str,
                                filters: Optional[Dict[str, str]] = None) -> str:
        return self.get_econ_model_by_type_by_id_url(project_id, "Depreciation", model_id, filters)

    def get_depreciation_model_by_id(self, project_id: str, model_id: str) -> Union[Item, None]:
        return self.get_econ_model_by_type_by_id(project_id, "Depreciation", model_id)

    def get_depreciation_assignments_by_id_url(self, project_id: str, model_id: str,
                                      filters: Optional[Dict[str, str]] = None) -> str:
        return self.get_econ_model_assignments_by_type_by_id_url(project_id, "Depreciation", model_id, filters)

    def get_depreciation_assignments_by_id(self, project_id: str, model_id: str) -> Union[ItemList, None]:
        return self.get_econ_model_assignments_by_type_by_id(project_id, "Depreciation", model_id)

    def post_depreciation_assignments_by_id(self, project_id: str, model_id: str, data: ItemList) -> ItemList:
        return self.post_econ_model_assignments_by_type_by_id(project_id, "Depreciation", model_id, data)

    def put_depreciation_assignments_by_id(self, project_id: str, model_id: str, data: ItemList) -> ItemList:
        return self.put_econ_model_assignments_by_type_by_id(project_id, "Depreciation", model_id, data)

    def delete_depreciation_assignments_by_id(self, project_id: str, model_id: str, data: ItemList) -> ItemList:
        return self.delete_econ_model_assignments_by_type_by_id(project_id, "Depreciation", model_id, data)

    def get_differentials_models_url(self, project_id: str, filters: Optional[Dict[str, str]] = None) -> str:
        return self.get_econ_models_by_type_url(project_id, "Differentials", filters)

    def get_differentials_models(self, project_id: str, filters: Optional[Dict[str, str]] = None) -> ItemList:
        return self.get_econ_models_by_type(project_id, "Differentials", filters)

    def get_differentials_model_by_id_url(self, project_id: str, model_id: str,
                                filters: Optional[Dict[str, str]] = None) -> str:
        return self.get_econ_model_by_type_by_id_url(project_id, "Differentials", model_id, filters)

    def get_differentials_model_by_id(self, project_id: str, model_id: str) -> Union[Item, None]:
        return self.get_econ_model_by_type_by_id(project_id, "Differentials", model_id)

    def get_differentials_assignments_by_id_url(self, project_id: str, model_id: str,
                                      filters: Optional[Dict[str, str]] = None) -> str:
        return self.get_econ_model_assignments_by_type_by_id_url(project_id, "Differentials", model_id, filters)

    def get_differentials_assignments_by_id(self, project_id: str, model_id: str) -> Union[ItemList, None]:
        return self.get_econ_model_assignments_by_type_by_id(project_id, "Differentials", model_id)

    def post_differentials_assignments_by_id(self, project_id: str, model_id: str, data: ItemList) -> ItemList:
        return self.post_econ_model_assignments_by_type_by_id(project_id, "Differentials", model_id, data)

    def put_differentials_assignments_by_id(self, project_id: str, model_id: str, data: ItemList) -> ItemList:
        return self.put_econ_model_assignments_by_type_by_id(project_id, "Differentials", model_id, data)

    def delete_differentials_assignments_by_id(self, project_id: str, model_id: str, data: ItemList) -> ItemList:
        return self.delete_econ_model_assignments_by_type_by_id(project_id, "Differentials", model_id, data)

    def get_emissions_models_url(self, project_id: str, filters: Optional[Dict[str, str]] = None) -> str:
        return self.get_econ_models_by_type_url(project_id, "Emission", filters)

    def get_emissions_models(self, project_id: str, filters: Optional[Dict[str, str]] = None) -> ItemList:
        return self.get_econ_models_by_type(project_id, "Emission", filters)

    def get_emissions_model_by_id_url(self, project_id: str, model_id: str,
                                filters: Optional[Dict[str, str]] = None) -> str:
        return self.get_econ_model_by_type_by_id_url(project_id, "Emission", model_id, filters)

    def get_emissions_model_by_id(self, project_id: str, model_id: str) -> Union[Item, None]:
        return self.get_econ_model_by_type_by_id(project_id, "Emission", model_id)

    def get_emissions_assignments_by_id_url(self, project_id: str, model_id: str,
                                      filters: Optional[Dict[str, str]] = None) -> str:
        return self.get_econ_model_assignments_by_type_by_id_url(project_id, "Emission", model_id, filters)

    def get_emissions_assignments_by_id(self, project_id: str, model_id: str) -> Union[ItemList, None]:
        return self.get_econ_model_assignments_by_type_by_id(project_id, "Emission", model_id)

    def post_emissions_assignments_by_id(self, project_id: str, model_id: str, data: ItemList) -> ItemList:
        return self.post_econ_model_assignments_by_type_by_id(project_id, "Emission", model_id, data)

    def put_emissions_assignments_by_id(self, project_id: str, model_id: str, data: ItemList) -> ItemList:
        return self.put_econ_model_assignments_by_type_by_id(project_id, "Emission", model_id, data)

    def delete_emissions_assignments_by_id(self, project_id: str, model_id: str, data: ItemList) -> ItemList:
        return self.delete_econ_model_assignments_by_type_by_id(project_id, "Emission", model_id, data)

    def get_escalations_models_url(self, project_id: str, filters: Optional[Dict[str, str]] = None) -> str:
        return self.get_econ_models_by_type_url(project_id, "Escalation", filters)

    def get_escalations_models(self, project_id: str, filters: Optional[Dict[str, str]] = None) -> ItemList:
        return self.get_econ_models_by_type(project_id, "Escalation", filters)

    def get_escalations_model_by_id_url(self, project_id: str, model_id: str,
                                filters: Optional[Dict[str, str]] = None) -> str:
        return self.get_econ_model_by_type_by_id_url(project_id, "Escalation", model_id, filters)

    def get_escalations_model_by_id(self, project_id: str, model_id: str) -> Union[Item, None]:
        return self.get_econ_model_by_type_by_id(project_id, "Escalation", model_id)

    def get_escalations_assignments_by_id_url(self, project_id: str, model_id: str,
                                      filters: Optional[Dict[str, str]] = None) -> str:
        return self.get_econ_model_assignments_by_type_by_id_url(project_id, "Escalation", model_id, filters)

    def get_escalations_assignments_by_id(self, project_id: str, model_id: str) -> Union[ItemList, None]:
        return self.get_econ_model_assignments_by_type_by_id(project_id, "Escalation", model_id)

    def post_escalations_assignments_by_id(self, project_id: str, model_id: str, data: ItemList) -> ItemList:
        return self.post_econ_model_assignments_by_type_by_id(project_id, "Escalation", model_id, data)

    def put_escalations_assignments_by_id(self, project_id: str, model_id: str, data: ItemList) -> ItemList:
        return self.put_econ_model_assignments_by_type_by_id(project_id, "Escalation", model_id, data)

    def delete_escalations_assignments_by_id(self, project_id: str, model_id: str, data: ItemList) -> ItemList:
        return self.delete_econ_model_assignments_by_type_by_id(project_id, "Escalation", model_id, data)

    def get_expenses_models_url(self, project_id: str, filters: Optional[Dict[str, str]] = None) -> str:
        return self.get_econ_models_by_type_url(project_id, "Expenses", filters)

    def get_expenses_models(self, project_id: str, filters: Optional[Dict[str, str]] = None) -> ItemList:
        return self.get_econ_models_by_type(project_id, "Expenses", filters)

    def get_expenses_model_by_id_url(self, project_id: str, model_id: str,
                                filters: Optional[Dict[str, str]] = None) -> str:
        return self.get_econ_model_by_type_by_id_url(project_id, "Expenses", model_id, filters)

    def get_expenses_model_by_id(self, project_id: str, model_id: str) -> Union[Item, None]:
        return self.get_econ_model_by_type_by_id(project_id, "Expenses", model_id)

    def get_expenses_assignments_by_id_url(self, project_id: str, model_id: str,
                                      filters: Optional[Dict[str, str]] = None) -> str:
        return self.get_econ_model_assignments_by_type_by_id_url(project_id, "Expenses", model_id, filters)

    def get_expenses_assignments_by_id(self, project_id: str, model_id: str) -> Union[ItemList, None]:
        return self.get_econ_model_assignments_by_type_by_id(project_id, "Expenses", model_id)

    def post_expenses_assignments_by_id(self, project_id: str, model_id: str, data: ItemList) -> ItemList:
        return self.post_econ_model_assignments_by_type_by_id(project_id, "Expenses", model_id, data)

    def put_expenses_assignments_by_id(self, project_id: str, model_id: str, data: ItemList) -> ItemList:
        return self.put_econ_model_assignments_by_type_by_id(project_id, "Expenses", model_id, data)

    def delete_expenses_assignments_by_id(self, project_id: str, model_id: str, data: ItemList) -> ItemList:
        return self.delete_econ_model_assignments_by_type_by_id(project_id, "Expenses", model_id, data)

    def get_fluid_models_url(self, project_id: str, filters: Optional[Dict[str, str]] = None) -> str:
        return self.get_econ_models_by_type_url(project_id, "FluidModel", filters)

    def get_fluid_models(self, project_id: str, filters: Optional[Dict[str, str]] = None) -> ItemList:
        return self.get_econ_models_by_type(project_id, "FluidModel", filters)

    def get_fluid_model_by_id_url(self, project_id: str, model_id: str,
                                filters: Optional[Dict[str, str]] = None) -> str:
        return self.get_econ_model_by_type_by_id_url(project_id, "FluidModel", model_id, filters)

    def get_fluid_model_by_id(self, project_id: str, model_id: str) -> Union[Item, None]:
        return self.get_econ_model_by_type_by_id(project_id, "FluidModel", model_id)

    def get_fluid_assignments_by_id_url(self, project_id: str, model_id: str,
                                      filters: Optional[Dict[str, str]] = None) -> str:
        return self.get_econ_model_assignments_by_type_by_id_url(project_id, "FluidModel", model_id, filters)

    def get_fluid_assignments_by_id(self, project_id: str, model_id: str) -> Union[ItemList, None]:
        return self.get_econ_model_assignments_by_type_by_id(project_id, "FluidModel", model_id)

    def post_fluid_assignments_by_id(self, project_id: str, model_id: str, data: ItemList) -> ItemList:
        return self.post_econ_model_assignments_by_type_by_id(project_id, "FluidModel", model_id, data)

    def put_fluid_assignments_by_id(self, project_id: str, model_id: str, data: ItemList) -> ItemList:
        return self.put_econ_model_assignments_by_type_by_id(project_id, "FluidModel", model_id, data)

    def delete_fluid_assignments_by_id(self, project_id: str, model_id: str, data: ItemList) -> ItemList:
        return self.delete_econ_model_assignments_by_type_by_id(project_id, "FluidModel", model_id, data)

    def get_operations_models_url(self, project_id: str, filters: Optional[Dict[str, str]] = None) -> str:
        return self.get_econ_models_by_type_url(project_id, "Operations", filters)

    def get_operations_models(self, project_id: str, filters: Optional[Dict[str, str]] = None) -> ItemList:
        return self.get_econ_models_by_type(project_id, "Operations", filters)

    def get_operations_model_by_id_url(self, project_id: str, model_id: str,
                                filters: Optional[Dict[str, str]] = None) -> str:
        return self.get_econ_model_by_type_by_id_url(project_id, "Operations", model_id, filters)

    def get_operations_model_by_id(self, project_id: str, model_id: str) -> Union[Item, None]:
        return self.get_econ_model_by_type_by_id(project_id, "Operations", model_id)

    def get_operations_assignments_by_id_url(self, project_id: str, model_id: str,
                                      filters: Optional[Dict[str, str]] = None) -> str:
        return self.get_econ_model_assignments_by_type_by_id_url(project_id, "Operations", model_id, filters)

    def get_operations_assignments_by_id(self, project_id: str, model_id: str) -> Union[ItemList, None]:
        return self.get_econ_model_assignments_by_type_by_id(project_id, "Operations", model_id)

    def post_operations_assignments_by_id(self, project_id: str, model_id: str, data: ItemList) -> ItemList:
        return self.post_econ_model_assignments_by_type_by_id(project_id, "Operations", model_id, data)

    def put_operations_assignments_by_id(self, project_id: str, model_id: str, data: ItemList) -> ItemList:
        return self.put_econ_model_assignments_by_type_by_id(project_id, "Operations", model_id, data)

    def delete_operations_assignments_by_id(self, project_id: str, model_id: str, data: ItemList) -> ItemList:
        return self.delete_econ_model_assignments_by_type_by_id(project_id, "Operations", model_id, data)

    def get_ownership_reversions_models_url(self, project_id: str, filters: Optional[Dict[str, str]] = None) -> str:
        return self.get_econ_models_by_type_url(project_id, "OwnershipReversion", filters)

    def get_ownership_reversions_models(self, project_id: str, filters: Optional[Dict[str, str]] = None) -> ItemList:
        return self.get_econ_models_by_type(project_id, "OwnershipReversion", filters)

    def get_ownership_reversions_model_by_id_url(self, project_id: str, model_id: str,
                                filters: Optional[Dict[str, str]] = None) -> str:
        return self.get_econ_model_by_type_by_id_url(project_id, "OwnershipReversion", model_id, filters)

    def get_ownership_reversions_model_by_id(self, project_id: str, model_id: str) -> Union[Item, None]:
        return self.get_econ_model_by_type_by_id(project_id, "OwnershipReversion", model_id)

    def get_ownership_reversions_assignments_by_id_url(self, project_id: str, model_id: str,
                                      filters: Optional[Dict[str, str]] = None) -> str:
        return self.get_econ_model_assignments_by_type_by_id_url(project_id, "OwnershipReversion", model_id, filters)

    def get_ownership_reversions_assignments_by_id(self, project_id: str, model_id: str) -> Union[ItemList, None]:
        return self.get_econ_model_assignments_by_type_by_id(project_id, "OwnershipReversion", model_id)

    def post_ownership_reversions_assignments_by_id(self, project_id: str, model_id: str, data: ItemList) -> ItemList:
        return self.post_econ_model_assignments_by_type_by_id(project_id, "OwnershipReversion", model_id, data)

    def put_ownership_reversions_assignments_by_id(self, project_id: str, model_id: str, data: ItemList) -> ItemList:
        return self.put_econ_model_assignments_by_type_by_id(project_id, "OwnershipReversion", model_id, data)

    def delete_ownership_reversions_assignments_by_id(self, project_id: str, model_id: str, data: ItemList) -> ItemList:
        return self.delete_econ_model_assignments_by_type_by_id(project_id, "OwnershipReversion", model_id, data)

    def get_pricing_models_url(self, project_id: str, filters: Optional[Dict[str, str]] = None) -> str:
        return self.get_econ_models_by_type_url(project_id, "Pricing", filters)

    def get_pricing_models(self, project_id: str, filters: Optional[Dict[str, str]] = None) -> ItemList:
        return self.get_econ_models_by_type(project_id, "Pricing", filters)

    def get_pricing_model_by_id_url(self, project_id: str, model_id: str,
                                filters: Optional[Dict[str, str]] = None) -> str:
        return self.get_econ_model_by_type_by_id_url(project_id, "Pricing", model_id, filters)

    def get_pricing_model_by_id(self, project_id: str, model_id: str) -> Union[Item, None]:
        return self.get_econ_model_by_type_by_id(project_id, "Pricing", model_id)

    def get_pricing_assignments_by_id_url(self, project_id: str, model_id: str,
                                      filters: Optional[Dict[str, str]] = None) -> str:
        return self.get_econ_model_assignments_by_type_by_id_url(project_id, "Pricing", model_id, filters)

    def get_pricing_assignments_by_id(self, project_id: str, model_id: str) -> Union[ItemList, None]:
        return self.get_econ_model_assignments_by_type_by_id(project_id, "Pricing", model_id)

    def post_pricing_assignments_by_id(self, project_id: str, model_id: str, data: ItemList) -> ItemList:
        return self.post_econ_model_assignments_by_type_by_id(project_id, "Pricing", model_id, data)

    def put_pricing_assignments_by_id(self, project_id: str, model_id: str, data: ItemList) -> ItemList:
        return self.put_econ_model_assignments_by_type_by_id(project_id, "Pricing", model_id, data)

    def delete_pricing_assignments_by_id(self, project_id: str, model_id: str, data: ItemList) -> ItemList:
        return self.delete_econ_model_assignments_by_type_by_id(project_id, "Pricing", model_id, data)

    def get_production_taxes_models_url(self, project_id: str, filters: Optional[Dict[str, str]] = None) -> str:
        return self.get_econ_models_by_type_url(project_id, "ProductionTaxes", filters)

    def get_production_taxes_models(self, project_id: str, filters: Optional[Dict[str, str]] = None) -> ItemList:
        return self.get_econ_models_by_type(project_id, "ProductionTaxes", filters)

    def get_production_taxes_model_by_id_url(self, project_id: str, model_id: str,
                                filters: Optional[Dict[str, str]] = None) -> str:
        return self.get_econ_model_by_type_by_id_url(project_id, "ProductionTaxes", model_id, filters)

    def get_production_taxes_model_by_id(self, project_id: str, model_id: str) -> Union[Item, None]:
        return self.get_econ_model_by_type_by_id(project_id, "ProductionTaxes", model_id)

    def get_production_taxes_assignments_by_id_url(self, project_id: str, model_id: str,
                                      filters: Optional[Dict[str, str]] = None) -> str:
        return self.get_econ_model_assignments_by_type_by_id_url(project_id, "ProductionTaxes", model_id, filters)

    def get_production_taxes_assignments_by_id(self, project_id: str, model_id: str) -> Union[ItemList, None]:
        return self.get_econ_model_assignments_by_type_by_id(project_id, "ProductionTaxes", model_id)

    def post_production_taxes_assignments_by_id(self, project_id: str, model_id: str, data: ItemList) -> ItemList:
        return self.post_econ_model_assignments_by_type_by_id(project_id, "ProductionTaxes", model_id, data)

    def put_production_taxes_assignments_by_id(self, project_id: str, model_id: str, data: ItemList) -> ItemList:
        return self.put_econ_model_assignments_by_type_by_id(project_id, "ProductionTaxes", model_id, data)

    def delete_production_taxes_assignments_by_id(self, project_id: str, model_id: str, data: ItemList) -> ItemList:
        return self.delete_econ_model_assignments_by_type_by_id(project_id, "ProductionTaxes", model_id, data)

    def get_reserves_categories_models_url(self, project_id: str, filters: Optional[Dict[str, str]] = None) -> str:
        return self.get_econ_models_by_type_url(project_id, "ReservesCategory", filters)

    def get_reserves_categories_models(self, project_id: str, filters: Optional[Dict[str, str]] = None) -> ItemList:
        return self.get_econ_models_by_type(project_id, "ReservesCategory", filters)

    def get_reserves_categories_model_by_id_url(self, project_id: str, model_id: str,
                                filters: Optional[Dict[str, str]] = None) -> str:
        return self.get_econ_model_by_type_by_id_url(project_id, "ReservesCategory", model_id, filters)

    def get_reserves_categories_model_by_id(self, project_id: str, model_id: str) -> Union[Item, None]:
        return self.get_econ_model_by_type_by_id(project_id, "ReservesCategory", model_id)

    def get_reserves_categories_assignments_by_id_url(self, project_id: str, model_id: str,
                                      filters: Optional[Dict[str, str]] = None) -> str:
        return self.get_econ_model_assignments_by_type_by_id_url(project_id, "ReservesCategory", model_id, filters)

    def get_reserves_categories_assignments_by_id(self, project_id: str, model_id: str) -> Union[ItemList, None]:
        return self.get_econ_model_assignments_by_type_by_id(project_id, "ReservesCategory", model_id)

    def post_reserves_categories_assignments_by_id(self, project_id: str, model_id: str, data: ItemList) -> ItemList:
        return self.post_econ_model_assignments_by_type_by_id(project_id, "ReservesCategory", model_id, data)

    def put_reserves_categories_assignments_by_id(self, project_id: str, model_id: str, data: ItemList) -> ItemList:
        return self.put_econ_model_assignments_by_type_by_id(project_id, "ReservesCategory", model_id, data)

    def delete_reserves_categories_assignments_by_id(self, project_id: str, model_id: str, data: ItemList) -> ItemList:
        return self.delete_econ_model_assignments_by_type_by_id(project_id, "ReservesCategory", model_id, data)

    def get_riskings_models_url(self, project_id: str, filters: Optional[Dict[str, str]] = None) -> str:
        return self.get_econ_models_by_type_url(project_id, "Risking", filters)

    def get_riskings_models(self, project_id: str, filters: Optional[Dict[str, str]] = None) -> ItemList:
        return self.get_econ_models_by_type(project_id, "Risking", filters)

    def get_riskings_model_by_id_url(self, project_id: str, model_id: str,
                                filters: Optional[Dict[str, str]] = None) -> str:
        return self.get_econ_model_by_type_by_id_url(project_id, "Risking", model_id, filters)

    def get_riskings_model_by_id(self, project_id: str, model_id: str) -> Union[Item, None]:
        return self.get_econ_model_by_type_by_id(project_id, "Risking", model_id)

    def get_riskings_assignments_by_id_url(self, project_id: str, model_id: str,
                                      filters: Optional[Dict[str, str]] = None) -> str:
        return self.get_econ_model_assignments_by_type_by_id_url(project_id, "Risking", model_id, filters)

    def get_riskings_assignments_by_id(self, project_id: str, model_id: str) -> Union[ItemList, None]:
        return self.get_econ_model_assignments_by_type_by_id(project_id, "Risking", model_id)

    def post_riskings_assignments_by_id(self, project_id: str, model_id: str, data: ItemList) -> ItemList:
        return self.post_econ_model_assignments_by_type_by_id(project_id, "Risking", model_id, data)

    def put_riskings_assignments_by_id(self, project_id: str, model_id: str, data: ItemList) -> ItemList:
        return self.put_econ_model_assignments_by_type_by_id(project_id, "Risking", model_id, data)

    def delete_riskings_assignments_by_id(self, project_id: str, model_id: str, data: ItemList) -> ItemList:
        return self.delete_econ_model_assignments_by_type_by_id(project_id, "Risking", model_id, data)

    def get_stream_properties_models_url(self, project_id: str, filters: Optional[Dict[str, str]] = None) -> str:
        return self.get_econ_models_by_type_url(project_id, "StreamProperties", filters)

    def get_stream_properties_models(self, project_id: str, filters: Optional[Dict[str, str]] = None) -> ItemList:
        return self.get_econ_models_by_type(project_id, "StreamProperties", filters)

    def get_stream_properties_model_by_id_url(self, project_id: str, model_id: str,
                                filters: Optional[Dict[str, str]] = None) -> str:
        return self.get_econ_model_by_type_by_id_url(project_id, "StreamProperties", model_id, filters)

    def get_stream_properties_model_by_id(self, project_id: str, model_id: str) -> Union[Item, None]:
        return self.get_econ_model_by_type_by_id(project_id, "StreamProperties", model_id)

    def get_stream_properties_assignments_by_id_url(self, project_id: str, model_id: str,
                                      filters: Optional[Dict[str, str]] = None) -> str:
        return self.get_econ_model_assignments_by_type_by_id_url(project_id, "StreamProperties", model_id, filters)

    def get_stream_properties_assignments_by_id(self, project_id: str, model_id: str) -> Union[ItemList, None]:
        return self.get_econ_model_assignments_by_type_by_id(project_id, "StreamProperties", model_id)

    def post_stream_properties_assignments_by_id(self, project_id: str, model_id: str, data: ItemList) -> ItemList:
        return self.post_econ_model_assignments_by_type_by_id(project_id, "StreamProperties", model_id, data)

    def put_stream_properties_assignments_by_id(self, project_id: str, model_id: str, data: ItemList) -> ItemList:
        return self.put_econ_model_assignments_by_type_by_id(project_id, "StreamProperties", model_id, data)

    def delete_stream_properties_assignments_by_id(self, project_id: str, model_id: str, data: ItemList) -> ItemList:
        return self.delete_econ_model_assignments_by_type_by_id(project_id, "StreamProperties", model_id, data)
