# DO NOT EDIT -- generated by scripts/generate_csv_functions.py from econModels.json + the mapper registry.
# Re-run that script after adding/removing a mapper or changing econModels.json.
"""Per-type CSV convenience functions (generated).

Thin, explicit wrappers over `registry.get_mapper(...)` so each econ-model type has a
named `<type>_to_csv_rows` / `<type>_from_csv_rows` pair -- matching the per-type function
convention used elsewhere in the package (e.g. `get_<type>_models`) rather than requiring
callers to reach for the generic `get_mapper`.
"""
from __future__ import annotations

from typing import Any, Dict, List, Optional

from .base import Context
from .registry import get_mapper


def actual_forecast_to_csv_rows(model: Dict[str, Any], context: Optional[Context] = None) -> List[Dict[str, str]]:
    """Convert one `ActualOrForecast` econ-model API dict to CSV rows (model-level export shape)."""
    return get_mapper('ActualOrForecast').to_csv_rows(model, context)


def actual_forecast_from_csv_rows(rows: List[Dict[str, str]]) -> Dict[str, Any]:
    """Reconstruct a `ActualOrForecast` econ-model API dict from its CSV rows."""
    return get_mapper('ActualOrForecast').from_csv_rows(rows)


def capex_to_csv_rows(model: Dict[str, Any], context: Optional[Context] = None) -> List[Dict[str, str]]:
    """Convert one `Capex` econ-model API dict to CSV rows (model-level export shape)."""
    return get_mapper('Capex').to_csv_rows(model, context)


def capex_from_csv_rows(rows: List[Dict[str, str]]) -> Dict[str, Any]:
    """Reconstruct a `Capex` econ-model API dict from its CSV rows."""
    return get_mapper('Capex').from_csv_rows(rows)


def date_settings_to_csv_rows(model: Dict[str, Any], context: Optional[Context] = None) -> List[Dict[str, str]]:
    """Convert one `Dates` econ-model API dict to CSV rows (model-level export shape)."""
    return get_mapper('Dates').to_csv_rows(model, context)


def date_settings_from_csv_rows(rows: List[Dict[str, str]]) -> Dict[str, Any]:
    """Reconstruct a `Dates` econ-model API dict from its CSV rows."""
    return get_mapper('Dates').from_csv_rows(rows)


def differentials_to_csv_rows(model: Dict[str, Any], context: Optional[Context] = None) -> List[Dict[str, str]]:
    """Convert one `Differentials` econ-model API dict to CSV rows (model-level export shape)."""
    return get_mapper('Differentials').to_csv_rows(model, context)


def differentials_from_csv_rows(rows: List[Dict[str, str]]) -> Dict[str, Any]:
    """Reconstruct a `Differentials` econ-model API dict from its CSV rows."""
    return get_mapper('Differentials').from_csv_rows(rows)


def expenses_to_csv_rows(model: Dict[str, Any], context: Optional[Context] = None) -> List[Dict[str, str]]:
    """Convert one `Expenses` econ-model API dict to CSV rows (model-level export shape)."""
    return get_mapper('Expenses').to_csv_rows(model, context)


def expenses_from_csv_rows(rows: List[Dict[str, str]]) -> Dict[str, Any]:
    """Reconstruct a `Expenses` econ-model API dict from its CSV rows."""
    return get_mapper('Expenses').from_csv_rows(rows)


def ownership_reversions_to_csv_rows(model: Dict[str, Any], context: Optional[Context] = None) -> List[Dict[str, str]]:
    """Convert one `OwnershipReversion` econ-model API dict to CSV rows (model-level export shape)."""
    return get_mapper('OwnershipReversion').to_csv_rows(model, context)


def ownership_reversions_from_csv_rows(rows: List[Dict[str, str]]) -> Dict[str, Any]:
    """Reconstruct a `OwnershipReversion` econ-model API dict from its CSV rows."""
    return get_mapper('OwnershipReversion').from_csv_rows(rows)


def pricing_to_csv_rows(model: Dict[str, Any], context: Optional[Context] = None) -> List[Dict[str, str]]:
    """Convert one `Pricing` econ-model API dict to CSV rows (model-level export shape)."""
    return get_mapper('Pricing').to_csv_rows(model, context)


def pricing_from_csv_rows(rows: List[Dict[str, str]]) -> Dict[str, Any]:
    """Reconstruct a `Pricing` econ-model API dict from its CSV rows."""
    return get_mapper('Pricing').from_csv_rows(rows)


def production_taxes_to_csv_rows(model: Dict[str, Any], context: Optional[Context] = None) -> List[Dict[str, str]]:
    """Convert one `ProductionTaxes` econ-model API dict to CSV rows (model-level export shape)."""
    return get_mapper('ProductionTaxes').to_csv_rows(model, context)


def production_taxes_from_csv_rows(rows: List[Dict[str, str]]) -> Dict[str, Any]:
    """Reconstruct a `ProductionTaxes` econ-model API dict from its CSV rows."""
    return get_mapper('ProductionTaxes').from_csv_rows(rows)


def reserves_categories_to_csv_rows(model: Dict[str, Any], context: Optional[Context] = None) -> List[Dict[str, str]]:
    """Convert one `ReservesCategory` econ-model API dict to CSV rows (model-level export shape)."""
    return get_mapper('ReservesCategory').to_csv_rows(model, context)


def reserves_categories_from_csv_rows(rows: List[Dict[str, str]]) -> Dict[str, Any]:
    """Reconstruct a `ReservesCategory` econ-model API dict from its CSV rows."""
    return get_mapper('ReservesCategory').from_csv_rows(rows)


def riskings_to_csv_rows(model: Dict[str, Any], context: Optional[Context] = None) -> List[Dict[str, str]]:
    """Convert one `Risking` econ-model API dict to CSV rows (model-level export shape)."""
    return get_mapper('Risking').to_csv_rows(model, context)


def riskings_from_csv_rows(rows: List[Dict[str, str]]) -> Dict[str, Any]:
    """Reconstruct a `Risking` econ-model API dict from its CSV rows."""
    return get_mapper('Risking').from_csv_rows(rows)


def stream_properties_to_csv_rows(model: Dict[str, Any], context: Optional[Context] = None) -> List[Dict[str, str]]:
    """Convert one `StreamProperties` econ-model API dict to CSV rows (model-level export shape)."""
    return get_mapper('StreamProperties').to_csv_rows(model, context)


def stream_properties_from_csv_rows(rows: List[Dict[str, str]]) -> Dict[str, Any]:
    """Reconstruct a `StreamProperties` econ-model API dict from its CSV rows."""
    return get_mapper('StreamProperties').from_csv_rows(rows)


__all__ = [
    'actual_forecast_to_csv_rows',
    'actual_forecast_from_csv_rows',
    'capex_to_csv_rows',
    'capex_from_csv_rows',
    'date_settings_to_csv_rows',
    'date_settings_from_csv_rows',
    'differentials_to_csv_rows',
    'differentials_from_csv_rows',
    'expenses_to_csv_rows',
    'expenses_from_csv_rows',
    'ownership_reversions_to_csv_rows',
    'ownership_reversions_from_csv_rows',
    'pricing_to_csv_rows',
    'pricing_from_csv_rows',
    'production_taxes_to_csv_rows',
    'production_taxes_from_csv_rows',
    'reserves_categories_to_csv_rows',
    'reserves_categories_from_csv_rows',
    'riskings_to_csv_rows',
    'riskings_from_csv_rows',
    'stream_properties_to_csv_rows',
    'stream_properties_from_csv_rows',
]
